### ISSUE TITLE
조도센서 이용해서 불 꺼지면 자동으로 에어컨 끄기

### ISSUE THREAD

**Issue by SeoJueun** [Buzzvil/hardware-lab#8]

**Comment by SeoJueun** [comment]
@SeoJungHong 주문한 조도센서 모듈은
BH1750 디지털 조도 센서 모듈 GY-302
입니다.
참고 부탁드려요~

**Comment by SeoJungHong** [comment]
- 라즈베리 파이의 I2C 통신 모듈 활성화
`/boot/config.txt` : `dtparam=i2c_arm=on` 를 추가한다.(기본적으로 주석 처리 되어있는데 이를 해제한다)
`/etc/modules` : `i2c-dev` 를 추가한다.

- I2C 통신이 활성화 되었는지 테스트
```
lsmod | grep i2c_
```

`i2c_bcm####(숫자)` 과 `i2c_dev` 가 검색되어야 한다.

- I2C Interface number 알아내기(I2C Bus의 아이디?) 
```
ls /dev/*i2c*
```
> pi2, pi3 에서는 `/dev/i2c-1` 출력됨. id = 1

- 필요한 패키지 설치
```
sudo apt-get install python-smbus i2c-tools
```

- 다른 I2C 디바이스(조도센서)와 정상적으로 연결되었는지 확인
```
sudo i2cdetect -y 1
```
> 여기의 1이 위에서 알아낸 I2C Interface number

실행 시 다음과 같이 특정 address에서 반응이 있어야 함.
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: 20 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

- Reference
https://raspberrypi.stackexchange.com/questions/61905/enable-i2c-on-ubuntu-mate-raspberry-pi-3
http://www.raspberrypi-spy.co.uk/2014/11/enabling-the-i2c-interface-on-the-raspberry-pi/
https://learn.sparkfun.com/tutorials/raspberry-pi-spi-and-i2c-tutorial

**Comment by SeoJungHong** [comment]
- I2C 통신시 사용하는 파일은 `/dev/i2c-1` -> docker run 때 마운트 시켜야 함
- 기존에 사용한 python-smbus 패키지는 python2 전용 -> smbus-cffi 로 변경

**Comment by SeoJueun** [comment]
완료
